version: '3.3'
services:
  varnish:
    build: .
    command: bash -c 'varnishtest test/*.vtc'
    environment:
        HOST: "nginx:80"
        PUBLIC_KEY: |-
            -----BEGIN PUBLIC KEY-----
            MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMWIrilCC8LEAhWwwVmlA7lgSH6VHLOy
            S9HFjIYiYKo6apbvrqwwOb1nZ1dyrAXgOUKBG8h2iWJWaqDqmoAFRScCAwEAAQ==
            -----END PUBLIC KEY-----
